### ISSUE TITLE
A way to describe that a lambda will be executed in place

### ISSUE THREAD

**Issue by KotlinIsland** [python/typing#1070]
Look at how mypy can't narrow the type in this situation:
```py
from typing import Callable

def run(fn: Callable[[], object]):
    fn()

for i in [1, "s"]:
    if isinstance(i, int):
        reveal_type(i)  # int
        run(lambda: reveal_type(i))  # object
```

In Kotlin this usage can be described with a contract:
```kt
fun run(fn: () -> object) {
    contract {
        callsInPlace(fn, InvocationKind.EXACTLY_ONCE)
    }
    fn()
}

for (i in listOf(1, "s"))
    if (i is Int)
        run { i + 1 )  // i is an Int here
```

I can't think of a situation where the [invocation kind](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.contracts/-invocation-kind/) would have any use in Pythons as I don't there there are any ways you can have a 'type effect' in a lambda.

So what about an `InPlace` type? used like:
```py
from typing import Callable, InPlace

def run(fn: InPlace[Callable[[], object]]):
    fn()

for i in [1, "s"]:
    if isinstance(i, int):
        reveal_type(i)  # int
        run(lambda: reveal_type(i))  # int
```

**Comment by hauntsaninja** [comment]
I'm not sure this is worth it, it's a fairly niche situation.

Note that while complaints about lambda do come up fairly often in mypy issues, I think:
a) there's reporting bias, since if you're not aware of late binding, it seems like "clearly a bug"
b) it's mostly in cases where mypy could avoid false positives by adding more heuristics, e.g. allow if the symbol is not later reassigned
c) in some cases, when mypy has an outright bug

From testing, I think pyright has implemented at least the reassignment heuristic. While obviously it won't cover your example here, maybe @erictraut has a more informed opinion on how far heuristics get us in practice (I'm also curious if pyright has any other tricks in this kind of situation).

(Also in the off chance we ever want to do something more explicit around lifetimes or mutability, we might regret a halfhearted not-widely-needed type-effect-thing)

**Comment by erictraut** [comment]
I agree with @hauntsaninja. 

Several months ago, I implemented code in pyright that determines whether a captured variable is potentially reassigned after the lambda (or inner function) on any code path. This eliminated the vast majority of false positives.

```python
def run(fn: () -> object):
    fn()

def func1(i: int | None):
    if i is not None:
        run(lambda: reveal_type(i))  # Pyright reveals: int
    else:
        i = None

def func2(i: int | None):
    if i is not None:
        run(lambda: reveal_type(i))  # Pyright reveals: int | None
    i = None
```

For the rare cases where this doesn't work (including the sample at the top of this thread), it's easy to work around the issue by assigning the narrowed value to a temp variable that is then captured by the lambda or inner function.

```python
for i in [1, "s"]:
    if isinstance(i, int):
        x = i
        run(lambda: reveal_type(x)) # int
```

**Comment by KotlinIsland** [comment]
Fair enough I guess it's not as important here as it is in Kotlin where lambdas aren't just a single expression.

Pylint also incorrectly warns on this situation with `W0640: Cell variable i defined in loop (cell-var-from-loop)`. I would like to see this but if you think it's extremely niche then I'll just close this.
