### ISSUE TITLE
About formal parameter is function, how to hint it?

### ISSUE THREAD

**Issue by HouLingLXH** [python/typing#1131]
For example:

def test(a: int, b:???):
    print(b(a))

def add( x:int):
    return x + 1

test(1, add)

About the ??? after b, how to hint the type of b is "(x:int) -> int" ？

**Comment by Zomatree** [comment]
You can use [`typing.Callable`](https://docs.python.org/3/library/typing.html#typing.Callable) here, in this example you would do `Callable[[int], int]`.

**Comment by srittau** [comment]
Please also see our discussion forum: https://github.com/python/typing/discussions

**Comment by HouLingLXH** [comment]
![image](https://user-images.githubusercontent.com/30954632/163297182-914ad584-19ef-4310-8057-2028679149bf.png)

![image](https://user-images.githubusercontent.com/30954632/163296909-617e67c3-1739-4e08-910d-8688ffa7e94b.png)

EventTest is the subclass of EventBase, how to fixed it?

**Comment by TeamSpen210** [comment]
`Callable` is somewhat unique in that the parameter types are [contravariant](https://peps.python.org/pep-0484/#covariance-and-contravariance), meaning that it accepts the specified class or its superclasses, not subclasses (which is covariant). It might seem odd, but if you think about it it makes sense. If your listener got given `Callable[[object], None]` that would work fine because that callable wouldn't use any `EventBase` functions. But if the callable was `Callable[[EventTest], None]`, that would be invalid because it might use `EventTest`-specific functions which `EventBase` doesn't support.

The fix is to use generic types:
```py
from typing import TypeVar
EventT = TypeVar('EventT', bound=EventBase)

def add_listener(self, event_class: type[EventT], want_do: Callable[[EventT], None]) -> None: ...
```
Then it can accept any subclasses, but the callable and `event_class` must match.
