### ISSUE TITLE
Link to CONTRIBUTING.md in README.md is dead

### ISSUE THREAD

**Issue by carmenbianca** [python/typing#1195]
In the root README.md file of this repository, there is a link to CONTRIBUTING.md at the bottom. This link is dead, and in the 1 minute I've spent looking, I could not find the file elsewhere.

**Comment by AlexWaygood** [comment]
Thanks! I deleted `CONTRIBUTING.md` in https://github.com/python/typing/pull/1192, because the information in it was all specific to contributing to typing_extensions, and the source code for that package now lives in [a separate repository](https://github.com/python/typing_extensions).

I've filed #1196 to fix the dead link.
