### ISSUE TITLE
for loop typing

### ISSUE THREAD

**Issue by Godwhitelight** [python/typing#1374]
The idea is to add typing to a for loop argument like described bellow.

```py
for ans: RR in resp.rr:
    answers.append(ans)
    if ans.rtype in QTYPE:
        db_record = data.DatabaseRecord(int(ans.rtype), str(ans.rname),
                                        str(ans.rdata), int(ans.rclass),
                                        int(ans.ttl), is_cached=True)
        cache(db_record)
```

**Comment by erictraut** [comment]
The standard way to do this is to declare the variable's type before the `for` loop.

```python
ans: RR
for ans in resp.rr:
    ...
```

Your proposal would require a grammar change to the Python language, so it wouldn't be backward compatible. It would be very unlikely to be accepted by the steering council.

Declaring the type of a loop variable is almost always unnecessary because its type can almost always be inferred from the iterator type (i.e. the type of the expression `resp.rr` in your example).

**Comment by JelleZijlstra** [comment]
As Eric said, this is usually unnecessary and there is an existing workaround.
