### ISSUE TITLE
List update allows slices but __setitem__() index is typed with SupportsIndex

### ISSUE THREAD

**Issue by andy-maier** [python/typing#1397]
The `index` argument of the built-in `list.__setitem__()` is typed with `SupportsIndex` (at least according to mypy), but the actual list update by index of course allows passing a slice:
```pycon
$ python
Python 3.9.16 (main, Dec  7 2022, 10:15:13) 
[Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> l1=['a','b']
>>> l1[0:2] = ['c','d']
>>> l1
['c', 'd']
>>> l1=['a','b']
>>> l1.__setitem__(slice(0,2),['c','d'])
>>> l1
['c', 'd']
>>> 
```

To my understanding, `SupportsIndex` does not represent a slice, but a single object that can be used as an index.

Could you please clarify this?

**Comment by AlexWaygood** [comment]
What specific code is causing mypy to emit an error for you? Mypy has no issues for the above snippet: https://mypy-play.net/?mypy=latest&python=3.11&gist=2b1ff6d43e92055fce7d55b317546759.

If you're confused about why mypy _permits_ this code, it's because `list.__setitem__` is an overloaded method in typeshed's stubs: https://github.com/python/typeshed/blob/ae0c9f9dadd72ee823d289416943a9109e24fe52/stdlib/builtins.pyi#L999-L1002

```py
from typing import TypeVar, Generic, MutableSequence, overload, Iterable
from typing_extensions import SupportsIndex

T = TypeVar("T")

class list(MutableSequence[_T], Generic[_T]):
    @overload
    def __setitem__(self, __key: SupportsIndex, __value: _T) -> None: ...
    @overload
    def __setitem__(self, __key: slice, __value: Iterable[_T]) -> None: ...
```

The first overload cannot apply in this context, so mypy looks at the second overload, and selects that one instead.
