### ISSUE TITLE
PEP544 makes it impossible to type-hint functions that return `Protocol`-classes.

### ISSUE THREAD

**Issue by randolf-scholz** [python/typing#1441]
According to [PEP544](https://peps.python.org/pep-0544/#type-and-class-objects-vs-protocols), 

> Variables and parameters annotated with Type[Proto] accept only concrete (non-protocol) subtypes of Proto.

This makes it impossible to properly annotate functions that create `Protocol` classes. As a trivial example, consider:

```python
from typing import Protocol

def top() -> type[Protocol]:  # error: Variable "typing.Protocol" is not valid as a type
    class Top(Protocol):
        pass
    return Top
```

For a non-trivial example, consider the following, which is part of the `Intersection`-PEP discussions: 

<details> <summary> Non-trivial example... </summary>

```python
from typing import TypeVarTuple, Intersection

protocols = TypeVarTuple("protocols")   
# technically we want TypeVarTuple("protocols", bound=type[Protocol])
# but bounds are not (yet) supported by TypeVarTuple.


# less sophisticated: merge_protocols(*protos: type[Protocol]) -> type[Protocol] ...
def merge_protocols(*protos: *protocols) -> Intersection[*Protocols]: ...
    """Creates the intersection of pairwise disjoint protocol classes.

    E.g. merge_protocols(Hashable, Sized) returns a `Protocol`-class equivalent
    to `Hashable & Sized`.

    merge_protocols() returns an empty Protocol class.
    """
````

</details>

One may define similar things even without `Intersection` available. As motivation, the PEP states that:

> The main reason for this is to allow instantiation of parameters with such type.

<details> <summary> Example from the PEP... </summary> 

```python
class Proto(Protocol):
    @abstractmethod
    def meth(self) -> int:
        ...
class Concrete:
    def meth(self) -> int:
        return 42

def fun(cls: Type[Proto]) -> int:
    return cls().meth() # OK
```

</details>

Since a `Protocol`-class may contain `@abstractmethod` annotated methods.  However, the given example is odd, because calling `cls()` is generally not safe here, as potentially infinitely many different classes with different `__init__` that require certain args/kwargs could match here. Moreover, non-`Protocol` classes implementing `Proto` could be abstract themselves as well.

**Comment by erictraut** [comment]
`Protocol` is a special form that changes the interpretation of a class definition. It indicates that it should be treated as a structural type rather than a nominal type for purposes of static type checking. `Protocol` is not a class in the static type and should not be treated as such. The type expression `type[Prototype]` doesn't make sense — just as `type[Generic]`, `type[Final]`, `type[NotRequired]`, and `type[ClassVar]` don't make sense. Treating `Prototype` as a class would open up a can of worms regarding subtyping relationships, so let's not go there.

The statement that you quote from PEP 544 above is not referring to the expression `type[Protocol]` but rather to the expression `type[Proto]` where `Proto` is a structural type. The authors of PEP 484 and 544 decided that assignability requirements for `type[X]` go beyond type consistency. Even though a class's type is _consistent_ with `type[X]`, it is not _assignable_ if you cannot directly call the assigned value to invoke its constructor. In my experience, this rule creates more problems than it solves, but I understand the reasoning behind it.
