### ISSUE TITLE
Support for Union[*TypeVarTuple]

### ISSUE THREAD

**Issue by pwuertz** [python/typing#1523]
I'm trying to annotate a method that only accepts a union of specific types, with the types specified via variadic generic. Although mypy supports variadic unpacking like `Tuple[*Ts]`, unpacking `Union[*Ts]` doesn't seem to work yet:

```python
import typing

Ts = typing.TypeVarTuple("Ts")

class Accepts(typing.Generic[*Ts]):
    # error: Unpack is only valid in a variadic position  [valid-type]
    def foo(self, x: typing.Union[*Ts]): ...

class A: ...
class B: ...
class C: ...
class Test(Accepts[A, B]): ...

Test().foo(A())  # ok
Test().foo(B())  # ok
Test().foo(C())  # should raise [arg-type] error
```

Mypy 1.7.1, Python 3.11

**Comment by erictraut** [comment]
This is simply a missing piece of functionality in mypy. I recommend closing this issue and opening a corresponding one in the mypy issue tracker to it gets the attention of the mypy maintainers. 

FWIW, the above code type checks as expected [in pyright](https://pyright-play.net/?code=JYWwDg9gTgLgBDAnmYA7A5gWAFA4CoDOcAvAsmugHR7ICmAagIZR4CuYANrQBQBEhvAJQ4cAYw6MCRAIKjRtMDALckKDJQDitVLSjBRAbQBUhALqCAXDjg24AYji6o0C3ACqqMI1EBrOMCIIVA5EOAA3Rg5gABN-VDhGcOZgRmj9OEgCYBhgIJsDCKjogFpVWlNrW2jaADM4GogIbgJaDhqAGjgAD1dVCkoPXNRjM0s4SgmRbHFJGVcJyjEJKTgAIXnJ6eWiAGENxa3ZuDxaAhhuWXlFAgNpTtXzfamTs%2B5BSgam6TfBGwcIHz4U7nd6fbirH5-OAAoGvUGNbg7SH2OAEAAWEFYHFiUEYAVocAMzHQpTopkcUGcUBwQA).

**Comment by matt-gardner** [comment]
Apologies if I'm missing something, but did pyright's behavior change since the above comment was written? When I click on the link to the pyright playground, I see a failure on line 7.

**Comment by erictraut** [comment]
Yes, pyright's behavior changed since the above comment. Unbeknownst to me, the PEP 646 authors removed the `Union[*Ts]` capability prior to the PEP's acceptance. I implemented pyright's PEP 646 support prior to this removal. Since the final version of the PEP removed the notion of `Union[*Ts]`, I likewise removed support for it in pyright.

If you would like to see `Union[*Ts]` become part of the type spec, that would require a new PEP, or at least a public discussion in the [Typing forum](https://discuss.python.org/c/typing/32), a proposed modification to [the spec](https://github.com/python/typing/tree/main/docs/spec), and approval by the Typing Council.
