### ISSUE TITLE
`get_type_hints` crashes on Python 2

### ISSUE THREAD

**Issue by evanunderscore** [python/typing#183]
I don't actually expect this to work, this is only a minor annoyance for code straddling Python 2 and 3. Right now I'm just monkey-patching it to `return {}`.

**Comment by gvanrossum** [comment]
(I chose to make it return None so you don't get tempted to actually use it.)

**Comment by bakkerthehacker** [comment]
This is a very useful function, even in python2.  I'm not sure that removing it was the only way to fix this.  

From what I can tell, there are 2 attrs (`__kwdefaults__` and `__annotations__`) that are missing from python 2 functions and are needed by `get_type_hints`.  Using `getattr` with defaults for these attrs allows `get_type_hints` to function properly.

**Comment by gvanrossum** [comment]
Oh, now I remember. It exists but always returns None.

Since there's no `__annotations__` there's not much useful information it could return.

Have you tried patching typing.py with that idea? Does it ever return anything useful that's not just the same as some function from `inspect`?

**Comment by bakkerthehacker** [comment]
> Since there's no `__annotations__` there's not much useful information it could return.

I don't agree that this is true.  While python2 lacks the ability to annotate using the new semicolon notation, it is possible to directly create `__annotations__` dictionaries for functions, classes and modules.  I would expect the typing module to handle these similarly to python3. 

> Have you tried patching typing.py with that idea?

Yes I have modified typing.py with these `getattr` changes and it does return the `__annotations__` properly.  

> Does it ever return anything useful that's not just the same as some function from inspect?

Yes, the main differences I am interested in are the `_ForwardRef` and `Optional` processing that `get_type_hints` does.  Also, I would expect any advanced class processing or module processing that `get_type_hints` does for python 3.6 to be different from `inspect`.

**Comment by gvanrossum** [comment]
Hm. So you are manually setting `__annotations__`? And you are doing that just so you can use `get_type_hints()`? That sounds rather far from the intended use case. What benefits do you get from that arrangement? (I'd never even considered this so maybe you just need to explain your use case better.)

**Comment by bakkerthehacker** [comment]
> Hm. So you are manually setting `__annotations__`?

Yes.  This practice is described here: http://python-future.org/func_annotations.html

>  And you are doing that just so you can use `get_type_hints()`?

No, not just `get_type_hints()`.  This is also used for type checking.  The code that manually sets the annotations must (for the moment) be compatible with both python 2 and 3.  The developers that work in python 3 really like type annotations and have used them quite a lot.  Some developers learned that these annotations can be applied manually and have done so using the `__annotations__` syntax to python2&3 code.  
We are also working on developing new custom (just another third-party from python's perspective) tools that uses these types, we want to run these tools in the python 2&3 code.  Python 3.6 introduces some new class and module annotations that this new tool wants to include.  `get_type_hints()` looked like a really promising function, instead of directly consuming the `__annotations__` attr in the tool directly.  However, with the current public versions of the `typing` backport, this `get_type_hints()` does not work.  

I hope this conveys my use case clearly.  The `__annotations__` are very useful to the python 2 code.  We are looking to migrate off of the manual attr and use the nice semicolon syntax at some point before the python2.7 EOL, but there is still a lot still do.

**Comment by gvanrossum** [comment]
I'm sorry, but I really don't want to encourage this kind of usage in
Python 2 by putting support back into the typing.py backport. Surely you
can write your own helper function that does what you need to do in Python
2 and just calls get_type_annotations() in Python 3.

**Comment by bakkerthehacker** [comment]
> I really don't want to encourage this kind of usage in Python 2

Is there a reason why?  Using `__annotations__` is very useful and is the only way to attach type annotations onto code that needs to run in python 2 and 3.  

While having separate code for python 2 and 3 works, having a unified behaviour between both would be desirable.  I think given your response, I will fork the `typing` backport package and restore the `get_type_hints` functionality.  This will allow the code that calls it to be much cleaner, IMO.

**Comment by gvanrossum** [comment]
What you are doing with `__annotations__` is essentially runtime typing. (At least, mypy won't understand annotations you stick into `__annotations__` at runtime.)

My plans are for annotations (PEP 3107) in the future to be (almost) exclusively used for static types (PEP 484, PEP 526). Sure, they can be introspected, but that's mostly for informational and debugging purposes. What you are calling a "backport" of the functionality is going in the opposite direction.

**Comment by bakkerthehacker** [comment]
> but that's mostly for informational and debugging purposes

`__annotations__` are much more than just debugging tools, IMO. Even in PEP 3107 under Use Cases lists several instances that I would consider much more than debugging or informational.   Predicate logic functions, Database query mapping, and RPC parameter marshaling seem to me to be quite a bit different than a debugging use.  Are these going to be removed from the PEP?  These use cases definitely seem like some sort of runtime typing.  

If static typing is the only (almost only) intended use case of annotations, then why should `get_type_hints()` exist at all? Will it be removed?  Does debugging or informational use not give enough of a reason to backport this?

**Comment by gvanrossum** [comment]
PEP 484 intends to gradually deprecate other uses of function annotations (PEP 3107). But the `__annotations__` attribute is here to stay and introspection of the annotations is occasionally useful. The `get_type_hints()` function is useful because introspection of the raw `__annotations__` reveals things like forward refs and doesn't capture the implied `Optional` due to a default of None.

There is no backport of PEP 3107. There is only Python 2 support for PEP 484, using comments, and the backport explicitly does not populate `__annotations__`.

**Comment by bakkerthehacker** [comment]
> There is no backport of PEP 3107.

I completely and respectfully disagree.  From a pragmatic point of view, setting `__annotations__` attrs *is* a backport, because it works in some situations.  Whether or not this practice is *encouraged* or looks good or is pythonic doesn't necessarily apply from this perspective.  I can understand not wanting to encourage setting `__annotations__` manually because it *is ugly*.  I don't really like it myself at all.  But it has practical applications.  mypy is not the only usecase for annotations.  python3 is not the only place where things can have `__annotations__` attrs.

**Comment by gvanrossum** [comment]
I think we've established that you're on your own here.

**Comment by bakkerthehacker** [comment]
Yes, I can see that this issue is indeed closed.  I think a meaningful discussion can still take place regarding annotations.
