### ISSUE TITLE
Does NewType function validates argument types?

### ISSUE THREAD

**Issue by moleschott** [python/typing#262]
I think there is weird behaviour about typing.NewType function.

I followed example on [https://www.python.org/dev/peps/pep-0484/#newtype-helper-function](url)

`tcp_packet = TcpPacketId(packet, 0)` fails as expected due to more positional argument.

However when I execute `tcp_packet = TcpPacketId("dummy")`, code works but tcp_packet variable is instance of string object.

This is unexpected behaviour, because we've already assigned `TcpPacketId = NewType('TcpPacketId', PacketId)` and wish TcpPacketId objects to be only instance of PacketId. I think constructor should raise 
a TypeError while executing in run-time.

I'm a little bit confused. Is this a bug or known and under control scenario?

**Comment by Michael0x2a** [comment]
This is actually expected behavior -- PEP 484 states that:

> ...at runtime, NewType('Derived', Base) returns a dummy function that simply returns its argument.

The idea behind `NewType` (and pretty much the rest of the typing module, for that matter) is that type annotations should have [minimal overhead and impact](https://www.python.org/dev/peps/pep-0484/#non-goals) on your code and serve mainly as useful metadata that can be checked by 3rd party tools. But yeah, the upshot is that `NewType` by design doesn't perform any runtime checks.

That said, if you tried checking your code using external type checkers such as [mypy](http://mypy-lang.org), you would end up seeing the following error if your code contained something like `TcpPacketId("dummy")`:

    test.py:15: error: Argument 1 to "TcpPacketId" has incompatible type "str"; expected "PacketId"

**Comment by moleschott** [comment]
Yes I know the idea. But it makes `typing.NewType("Dummy", str)` makes useless for API type runtime projects.

**Comment by gvanrossum** [comment]
Yes, `typing.NewType()` does not do anything useful at runtime. That is by design. It is however trivial to write your own function that does what you want. That is not the focus of the typing module however (collecting runtime type information is not a goal, just a side effect in cases where it is feasible).
