### ISSUE TITLE
Proposal: ContextManager interface

### ISSUE THREAD

**Issue by ahaven** [python/typing#274]
Because context managers are a language feature (for use in `with` blocks), typing should expose an interface class for them like it does with Dict, List, etc.

The typeshed for contextlib defines an interface for a ContextManager because it needs it in the return type for `contextlib.contextmanager`, but it seems like the kind of thing that should be in typing, not in a random stub.

**Comment by gvanrossum** [comment]
Yeah, and in Python 3.6 there's contextlib.AbstractContextManager in the
stdlib, from which typing.ContextManager inherits if it exists, and
otherwise typing doesn't define ContextManager at all. I guess what we
should do is, if contextlib.AbstractContextManager *doesn't* exist (i.e.
3.5 or earlier), typing.ContextManager should just fake one.

**Comment by JelleZijlstra** [comment]
I was just going to propose what Guido is suggesting above (based on discussion in python/typeshed#1200). Since this issue has already been open for months with no objection to the idea, I'll send a PR instead.
