### ISSUE TITLE
Recommend reveal_type in PEP 484

### ISSUE THREAD

**Issue by ilevkivskyi** [python/typing#277]
When #136 will be fixed, it will be nice to have something that could be used in place of `issubclass` for "experimentation" with types. Mypy already provides such a function -- `reveal_type`. I think it works very well and maybe it is a good idea to add a recommendation to PEP 484 that static type checkers should provide a function to reveal the inferred types? Or maybe even add a function

``` python
def reveal_type(obj):
    print('Runtime type is:', getattr(obj, '__orig_class__',  type(obj)))
    return obj
```

to `typing.py` so that it can be used for this purpose by other type checkers.

**Comment by srittau** [comment]
I wish `reveal_type()` was a Python builtin. Often when I test code, I have to temporarily comment out reveal_type calls, which is a bit annoying.

**Comment by sobolevn** [comment]
I use this hack:

```python
from typing import TYPE_CHECKING

if not TYPE_CHECKING:
   globals()['reveal_type'] = print
```

**Comment by gvanrossum** [comment]
I support making it a building. File a bpo issue and write a PR and I will add it.

**Comment by erictraut** [comment]
If `reveal_type` is added as an actual builtin call, its full type signature will need to be formalized.

Would you be open to reveal_type returning a str (the actual revealed type) rather than returning the value passed as an input argument?

Pyright currently implements `reveal_type` such that the return type of the call is a literal string value of the revealed type.

This allows us to use it in test cases, like this:
def func(x: int, y: str):
   z = x if x > 3 else y
   t1: Literal['int | str'] = reveal_type(z)

We use this in thousands of places within pyright's test suites. It would be significant work to change this.

**Comment by gvanrossum** [comment]
Hm. In mypy IIRC reveal_type(x) returns x. This makes it possible to wrap arbitrary subexpressions in it without changing their meaning. I would regret losing this.

**Comment by gvanrossum** [comment]
You could introduce a new helper with the desired meaning in a pyright-specific header.

**Comment by erictraut** [comment]
> This makes it possible to wrap arbitrary subexpressions in it without changing their meaning

Oh, that's clever. I hadn't considered that.

OK, we can introduce a new helper.

**Comment by JelleZijlstra** [comment]
I am implementing this by adding `typing.reveal_type`:
- https://bugs.python.org/issue46414
- https://github.com/python/cpython/pull/30646
- https://mail.python.org/archives/list/typing-sig@python.org/thread/YIZ3BKBQZVBTZH6GUA2EBOSWN7LAHE6M/

**Comment by JelleZijlstra** [comment]
This will be in Python 3.11 and the next release of typing-extensions.

https://docs.python.org/3.11/library/typing.html#typing.reveal_type
