### ISSUE TITLE
Final classes and member functions

### ISSUE THREAD

**Issue by dgoldstein0** [python/typing#286]
In some languages (e.g. java) it's possible to declare a class as final so that it can't be subclassed; similarly, it's possible to declare functions as `final` so that they can't be overridden by sublclasses. It would be great if typing could support this - so that classes could be annotated as final or their functions as final, and then tools like mypy could enforce it.

E.g.

```
@final
class Foo(object):
  pass

# type error
class Bar(Foo):
  pass
```

(reposting from https://github.com/python/mypy/issues/2032)

**Comment by gvanrossum** [comment]
It's an interesting idea. In Python's past things like this have been
proposed many times, but usually with the idea that a metaclass would have
to be added that enforces it (like with `@abstractmethod`). I wonder if
(like that) this should live in the `abc` module, possibly with an
implementation that enforces it. But the type checker could still enforce
it too. Alternatively it could live in typing and be purely a type checker
feature.

OTOH Wouldn't a comment (plus a note in any docs for the class)  be just as
effective? (Not, I guess, if you have an existing class or method that you
want to change to be final -- the `@final` decorator would allow you to
find any violations quicker than a grep, perhaps, and catch future
violations.)

**Comment by dgoldstein0** [comment]
yeah, I really want this for the enforcement use case.  I suppose failure
at runtime would work most of the time because classes are usually declared
in module scope but then you need some test that everything can be
imported; I suppose I'd trust a type checker to actually complain about all
usages in the case that I had some code which turned out not to be tested
at all.

**Comment by gvanrossum** [comment]
Given the (relative) uniqueness of your use case you're probably better off
hacking your own metaclass. But I believe I've said that before. :-)

**Comment by dgoldstein0** [comment]
You have, but at the same time you suggested I come here to too

**Comment by gvanrossum** [comment]
Yeah, so we can gauge interest.

**Comment by dgoldstein0** [comment]
At the moment I'm thinking it's probably easier to write a linter for my
use case.  But of course if this became a mypy feature it'd be less code to
just use that.

**Comment by elazarg** [comment]
`final` can be used similarly to the `sealed` feature in Scala, declaring a class to be only inheritable in the current file. this way the type checker can treat it as a Union over the subclasses (e.g. finding dead code, non-exhaustive overload/conditionals, more precise flow-sensitive recommendation etc.), without the need for awkward bookkeeping in a Union. In particular it will be suitable for `Expression` and `Statement` in mypy source code.

**Comment by JukkaL** [comment]
@elazarg I agree that the semantics you described would be nice.

**Comment by sobolevn** [comment]
I have release a utility library that can make classes `final`: https://github.com/wemake-services/final-class

**Comment by AgileInstitute** [comment]
The purpose of the sealed/final keywords is the same as making something in C++ nonvirtual: It allows you to improve the performance of a bottlenecked bit of code. As I understand it, method lookup in Python is always...well, a lookup. No performance benefit. So this run-time check is a rather weird, un-Pythonic hack. 

Rather than creating a run-time failure to enforce something, I'd recommend providing the consumers of your class with some clear tests that give examples of how your code is to be properly used. If this is a team you have influence over, then perhaps provide some guidance via lunch-n-learn sessions, pair-programming, or mob-programming on basic OO principles, S.O.L.I.D., patterns wisdom (e.g., "Favor delegation over inheritance" --GoF), and Beck's Four Rules of Simple Design (e.g., "Testability trumps everything else, because everything else is made malleable through tests." -- me, just now).

**Comment by elazarg** [comment]
Final functions and classes allow you to reason better about the behavior of the program, making your program easier to understand. Being able to e.g. inline function calls is just one consequence.

This doesn't mean of course that runtime failures is the right way to implement such feature.

**Comment by AgileInstitute** [comment]
I think I get what you're saying. As an early Java developer, I noticed that it was both a blessing and a curse to have everything be virtual. I made a lot of mistakes, misinterpreting OO. My first OO training went with the "better mousetrap" approach, which is strange because Design Patterns was already published, so the industry already knew that we should favor delegation over inheritance. 

It's almost never a good idea to override existing implementation. I can stay philosophical and say "it breaks LSP" but I'm a pragmatist, so I'd say something more like: You've decided that your new subclass is one of these things, but that you [think you] know better than the authors of that implementation. It's a huge source of defects. 

The only legit reason I've found for overriding existing implementation is in creating test-doubles. I suppose sealed/final are effective shortcuts for saying "this whole class is nonvirtual - leave it be." That makes sense. 

That said, declaring something as nonvirtual (or, in .Net, not declaring it virtual) makes a lot of sense when it's a coherent part of the language. But with languages like Python, Ruby, JavaScript, I can't rely on a compiler, so I rely on tests. Like a compiler checking static information ("is this what it should be?") tests check run-time behaviors ("does this behave as I expect?") which is what we really need to know. 

In fact, writing a test first (e.g., TDD or BDD) is exactly the way I "reason better about the behavior of the program." I don't merely think "this should occur," I record that thought in a "test" (an executable specification, really). Ergo, I can work safely and efficiently in any of those languages. My tests serve as a superset of the functionality of the compiler. The tests I write differ depending on the language. Haskell would require far fewer tests than JavaScript, for example.

**Comment by AgileInstitute** [comment]
All _my_ specs & cukes execute, and pass. YMMV. :-) 

They test what _does_ occur. I can't tell my code what _not_ to do. It just does what I tell it, of course. I can test that it does the right thing when something bad happens with some other bit of software, like when a developer who isn't on my team writes some buggy code. Which, sadly, happens all the time. 

For me, the compiler is the first line of defense against defects. Tests are the 2nd. Compilers don't catch logical branching errors. We write > when we meant >=, or 8 when we meant 7. Or we misread a ! and add our code to the wrong branch. (Oh, if I had a time-machine, I'd beg for a _not_ keyword instead of the bang. And I'd invest in Google stock...) 

I get a kick out of watching pairs of developers debate these things. "Is it 7? Or 8? Well, if we use >= then it's 8...right?" _Shut up and run the effing test!_ If they don't trust the test, then they fix it, or write another. **_Tests are cheap._**

TDD is a thinking process. Behaviors are _implemented_ in the implementation, but _described_ in the tests. (Important distinction that's often missed.) It's the same amount of thinking either way, except that we don't just let all the permutations of desired behaviors float around in our heads; we record them so no one (including us!) will come along and break them later. We don't have to re-think about the same tiny scenario, ever. It's right there, in a test, documenting and checking that behavior. 

I'm guessing that by "much stronger a statement" is that you're pointing out that compiler-time checking keep _developers_ from doing the wrong thing. It's "thinking in types" which is also quite powerful, and foundational. 

Tests (plural...one needs a thorough suite) also keep developers from writing the wrong logic now, or altering something incorrectly, later, when code needs to change to make room for some new functionality. 

If the Python community feels the need for stronger type-checking, great. Those who want (or need) duck-typing will just move over to Ruby. 

I gave up language wars decades ago. To me, different languages are for different types of software. The ultimate aim is to assure quality. Compilers catch syntax and type errors, tests catch logic and refactoring errors. If I don't have a compiler, I lean more on tests. If I have a strong typing system and I'm writing stateless functions, I can skip whole categories of tests. But I still feel the need to test _my_ code's _behaviors_. 

Example where testing is critical: Imagine you're building a C# framework for others to use: Complex numbers, or something similar, where it would make a lot of sense to have immutable data objects, and perhaps overloaded operators, or side-effect-free methods, or operators as named Method Objects, or whatever. Anyway, you decide you want to override object.Equals(object). The compiler is going to let anyone pass anything into that method. How would you test it? What needs to be true?

People often view testing as "the tester's job" or as "extra work." Traditionally, that was the case, but now it's a thinking process. "What if they're different types?" "What if I add these to a HashMap...?" Rather than immediately writing the solution (and having to keep various permutations in your head) we record them in a "test". Really, in this example, an engineering specification.

With a test-first approach, the test is a client of the code, so it serves as example of how the service was intended to be used. If there's no compile-time flag to be raised, then often an exception can be raised at run-time. I can test that it's raised in the right situations. 

Okay, before I get too far off-track, a summary: If there's a built-in way for the compiler to tell me and/or my API's consumers about a mistake, great. If not, I build tests that will tell me when I made a mistake, and I'll test in clear and reasonable exceptions to tell my API's consumers about their mistakes.

**Comment by gvanrossum** [comment]
@AgileInstitute Please stop lecturing.

**Comment by AgileInstitute** [comment]
My apologies. Got a little off-track.

**Comment by NeilGirdhar** [comment]
@dgoldstein0 I've been working on a base class (not a metaclass) that does various related checks.  I've considered a final method decorator (https://github.com/NeilGirdhar/ipromise).  If this looks interesting to you, please feel free to add a final decorator and check in the base class.
