### ISSUE TITLE
Callable and Tuple should be subclassable.

### ISSUE THREAD

**Issue by ilevkivskyi** [python/typing#299]
One can subclass ``collections.abc.Mapping`` as well as ``typing.Mapping[str, int]``. However, it is currently prohibited to subclass ``typing.Callable`` and ``typing.Tuple``:
```python
class C(collections.abc.Callable): ...  # works
class C(typing.Callable): ...           # fails

class C(typing.List[T]): ...            # works
class C(typing.Tuple[T, ...]): ...      # fails
```
I think that both ``Callable`` and ``Tuple`` should be subclassable (at least in the simple form shown above).

@gvanrossum If you agree, then you can assign this issue to me.

**Comment by gvanrossum** [comment]
I'm not entirely against this, but IIRC this is intentional, since these
are not plain generic classes. Doing the right thing in the type checker
might be difficult. I think Callable should basically be treated as a duck
type (__call__) and if you want to subclass Tuple you should subclass tuple
instead. Probably. Maybe @JukkaL has more thoughts?

**Comment by JukkaL** [comment]
Early prototypes of `typing` actually supported subclassing `Tuple[...]`. I think that it's as reasonable as subclassing `List[...]`, which is already supported. Subclassing `tuple` is not really a good alternative because then you can't specify the item types or the number of items, and instead it falls back to `Tuple[Any, ...]`. 

I think that `Callable` should use structural subtyping -- if `__call__` is defined, it's a callable. Explicitly subclassing it seems kind of reasonable as well, for consistency with the `collections.abc.Callable` ABC, but it would be less useful than subclassing `Tuple[...]`.
