### ISSUE TITLE
Allow instantiation of generic collections

### ISSUE THREAD

**Issue by ilevkivskyi** [python/typing#367]
Currently there are many places where we prohibit instantiation of generic versions of concrete collections, like
```python
    if _geqv(cls, List):
        raise TypeError("Type List cannot be instantiated; "
                                  "use list() instead")
```
This prohibits things like ``List[int]()``, ``Deque[int]()``, etc. As I remember the reason for this was that ``List[int]`` was slow. But now types are cached. Are there any other reasons to prohibit this? If not, then I propose to remove this limitation. Anyway things like ``Node[int]()`` are already allowed both in mypy and in typing.

**Comment by gvanrossum** [comment]
Would `List[int]()` it return an instance of `list` or of `List[int]`? I'm against the latter, because even an empty subclass of `list` will incur a significant overhead compared to the plain `list`.

**Comment by ilevkivskyi** [comment]
I also think it should be an instance of plain ``list`` (and plain ``collections.deque`` etc. for other classes).

**Comment by gvanrossum** [comment]
Then let's draft a patch to PEP 484 first

**Comment by markshannon** [comment]
I would prefer that the prohibition on instantiation remains.
Firstly a type is not a class. `List[int]` is not `list`, and type-hints should be kept distinct from the runtime values.
If I want a list of ints, then
`x: List[int] = []`
describes that perfectly.
If we allow
`x = List[int]()` 
are type checkers supposed to infer that l has type `List[int]`? 
PEP 484 says no, as there is no annotation, thus `x` is implicitly typed `Any`.

**Comment by gvanrossum** [comment]
I didn't intend the PEP to say that x *must* be inferred as `Any` -- where do you read that? Certainly mypy make that inference when using a non-builtin class:
```python
from typing import Generic, TypeVar
T = TypeVar('T')
class Node(Generic[T]): 
    def __init__(self):
        self.left = None  # type: Node[T]
        self.right = None  # type: Node[T]
def foo() -> None:
    root = Node[int]()
    reveal_type(root)  # Shows Node[int]
```

**Comment by markshannon** [comment]
You're right, it is reasonable to infer from `x = []` that `x` is a list.

I still don't like instantiating types though, mainly from wanting to keep classes and types separate.
Also, will people expect that
```python
x: List[int] = []
x.append("Hi")
```
raises a `TypeError`? 
Saying no seems to me violate the principle of least surprise, but saying yes has significant performance implications.

**Comment by ilevkivskyi** [comment]
As I understand, people were asking to allow:
```python
n = Node[int]()
```
as a short notation for
```python
n: Node[int] = Node()
```
only because it is shorter (``Node`` is not duplicated). So that for ``list``, ``dict`` etc. one will not gain anything from this. Thus we could keep prohibiting instantiating ``List[int]``, but maybe we could allow:
```python
d = DefaultDict[str, int]()
```
as a short notation (or "syntactic sugar") for
```
d: DefaultDict[str, int] = collections.defaultdict()
```
and also for ``deque`` and potentially (see PR #366) ``Counter`` and ``ChainMap``.

**Comment by markshannon** [comment]
I think we should be consistent, so if we are going to allow `d = DefaultDict[str, int]()` then we should allow `x = List[int]()`.

**Comment by gvanrossum** [comment]
Another advantage of allowing `List[int]()` is that this can be used in places where using an annotation instead would require a separate line, e.g. when passing an argument to a generic function.

There is still a slight difference between the (proposed) result of `List[int]()` and that of `Node[int]()` -- the latter has a `__class__` whose MRO includes `Generic`, while for `List[int]()` we're proposing not to do that. I think it's okay though; the runtime `__class__` for instances produced by `Node[int]()` and `Node[str]()` are the same (both point to `Node`).

We will have to be careful with subclasses of `List` though -- their instances should not be plain lists.

Re: Mark's question whether people should expect a runtime error for
```python
x: List[int] = []
x.append("Hi")
```
I think not -- it's no different from
```python
def f(x: List[int]): ...
f(["Hi"])
```
The type error is reported by the type checker but the runtime is unaffected.

**Comment by markshannon** [comment]
@gvanrossum I agree with you about what users *should* expect. My comment was about what they *will* expect.
I would like the differences between types and classes to be apparent as possible, to discourage people from forming misleading mental models.

Forcing people to write `d: DefaultDict[str, int] = defaultdict()` does make the distinction clear, but I have to concede that `d = DefaultDict[str, int]()` is shorter.
"explicit is better than implicit" or "practicality beats purity"?

**Comment by ilevkivskyi** [comment]
I am also in favor of clear distinction between types and classes (I even added a section on this to PEP 483: www.python.org/dev/peps/pep-0483/#types-vs-classes), but I think that it is OK to allow this as "syntactic sugar". PEP 484 already discusses "type erasure", we should state clearly that ``d = DefaultDict[str, int]()`` is just a short form that is _only_ allowed for types that are generic forms of runtime classes.

**Comment by JukkaL** [comment]
Mypy used to support code like `x = List[int]()` before PEP 484. I don't like the idea of resurrecting this syntax, for various reasons:

* Even if there is less overhead than previously, `List[int]()` is still going to be slower than `[]`.
* `x = List[int]()` vs. `x: List[int] = []` is much less of a conciness win compared to `x = UserDefinedClassName[int]()` vs. `x: UserDefinedClassName[int] = UserDefinedClassName()`, since there is no need to duplicate a potentially verbose class name. (Also I don't think that it's a readability win, which is more important.) Basically I think that the current syntax is already fine for lists, dictionaries and sets, which are the most common cases where this would be useful.
* It would arguably introduce more stylistic inconsistency and syntactic complexity. There would be two reasonable ways to spell `x: List[int] = []`, with somewhat complex tradeoffs -- one would be more efficient but would require a few additional keystrokes to spell, whereas the other would be slightly more compact and consistent with how you'd use a user-defined generic class. In other words, there would be no one obvious way to do this very common thing any more. I don't think that consistency with user-defined classes is important, since user-defined generic classes don't seem to be very common in typical code, and the syntax we've always used for built-in types is special anyway (including `[]` and `{}`). That's fine since built-in classes are used all over the place.
* If people would start using `x = List[int]()` and other similar things widely, statically typed code would arguably start looking more alien to people not familiar with it, since even common idioms like `x = []` may look very different. I'd prefer that static typing would usually just *add* things to legacy code (for example, adding a type annotation) instead of *changing* things to a different syntax.

**Comment by ilevkivskyi** [comment]
@JukkaL I agree with you about built-in classes, but what do you think about stdlib containers: ``defaultdict``, ``deque``, and potentially (see PR #366) ``Counter`` and ``ChainMap``? Should they follow the rules for user defined classes or rules for built-ins? I think they should behave like user defined classes (since in some sense they are).

Also, Mark says that we should be consistent, but it seems to me that disallowing the short form for built-ins is a simple and easy to remember exception.

**Comment by JukkaL** [comment]
I'm fine with using the rules for user-defined classes also for `defaultdict`, `deque` and perhaps other classes that have no special syntax for constructing instances. These are used relatively infrequently so they won't have a major impact on what code looks like either way, and the current syntax for `defaultdict` in particular is a little awkward.
