### ISSUE TITLE
Define Shape/ShapedDict type

### ISSUE THREAD

**Issue by item4** [python/typing#466]
I'm sorry about my poor english. I want to talk by code.

### Shape

```py3
from typing import *

import attrdict

UserRecord = Shape[{
    'name': str,
    'email': str,
    'age': Optinal[int]
}]

class U(NamedTuple):
    name: str
    email: str

class Troll:
    pass

me: UserRecord = U('John', 'john@example.com')  # OK
you: UserRecord = attrdict.AttrDict(some_dict)
doge: UserRecord = Troll()  # fail
```

### ShapedDict

```py3
from typing import *

Account = ShapedDict[{
    'id': str,
    'password': str,
    'name': str
    'age': int,
    'sex': Optinal[str],
    'addresses': List[Address],
}]
myinfo: Account = {'id': '123', 'password': 'supersecret', 'name': 'John', 'age': 17, 'addresses': []} # OK
yourinfo: Account = res.json()  # maybe..?
suck: Account = {'foo': 'bar'}  # fail
```

## You can find similar one from..

* [prop-types: shape](https://www.npmjs.com/package/prop-types)
* [TypeScript: interface](https://www.npmjs.com/package/prop-types)

## Why it needed?

1. autocomplete key on IDE.
2. typecheck for object attr and dict items (`typing.Dict` can not cover alls)

**Comment by ilevkivskyi** [comment]
mypy already provides most of this functionality by ``TypedDict``, it is not yet in ``typing`` (since it is still considered experimental/beta) but it is already quite stable and you can use it as ``from mypy_extensions import TypedDict``. Please read the [docs here](http://mypy.readthedocs.io/en/latest/kinds_of_types.html#typeddict), if this is what you want, then please close this issue.

**Comment by item4** [comment]
OK. I didn't know `mypy_extensions`. Thanks
