### ISSUE TITLE
Installing typing backport on conda

### ISSUE THREAD

**Issue by smarie** [python/typing#469]
Hello there, we found this strange bug on conda distribitions.
On python 3.5.2 (conda, windows64):

```python
from typing import Optional, Type
Optional[Type]
```

yields

```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\envs\typing\lib\typing.py", line 649, in __getitem__
    return Union[arg, type(None)]
  File "C:\Anaconda3\envs\typing\lib\typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "C:\Anaconda3\envs\typing\lib\typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "C:\Anaconda3\envs\typing\lib\typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "C:\Anaconda3\envs\typing\lib\typing.py", line 1077, in __subclasscheck__
    if super().__subclasscheck__(cls):
  File "C:\Anaconda3\envs\typing\lib\abc.py", line 225, in __subclasscheck__
    for scls in cls.__subclasses__():
TypeError: descriptor '__subclasses__' of 'type' object needs an argument
```

and with manual install of `typing` backport module it does not work better, whether done with pip (`pip install typing`) or conda (`conda install typing`).

**Comment by smarie** [comment]
Apparently this is due to the fact that conda still relies on the base module and not the backport. A solution (really not the best but it seems to work) is to delete the `Lib/typing.py` file (the base one) in your conda environment so that conda now searches in `site-packages` and finds the backport at `site-packages/typing.py`.

If anyone has a better solution don't hesitate to publish it :)

(initial bug found [here](https://github.com/smarie/python-autoclass/issues/4))

**Comment by ilevkivskyi** [comment]
Yes, this is related to the fact that you can't install backports with the same names as modules already in stdlib. You can try installing ``typing_extensions`` (which basically tries to work around this, plus you get some new experimental features), but I think it is not on ``conda`` yet.

**Comment by episodeyang** [comment]
I tried to install `typing_extensions` from `master`, but this error is still there.

**Comment by ilevkivskyi** [comment]
Yes, it looks like ``typing_extensions`` just re-export ``typing.Type`` if there is one. I think the problem is that ``Type`` inherits from ``type`` in one of older versions. On the other hand I am not sure we can _always_ define ``Type`` as it is defined in the the latest version.

Maybe others have some ideas, but I would propose to consider updating to the latest version of Python (3.6.2 currently), there are variable annotations and asynchronous generators/comprehensions :-)

**Comment by gvanrossum** [comment]
Presumably the typing.py you get is always from Python 3.5.2. Could you
update the Python version to 3.5.3 or 3.5.4? Both have been out for some
time (January and August this year, respectively). The only other
alternatives I can think of are always setting PYTHONPATH to point to a
custom copy of the latest typing.py (a big pain) or just living with not
using things that don't work with that version -- after all you're stuck
with whatever's in the stdlib for everything else too.

**Comment by episodeyang** [comment]
@ilevkivskyi @gvanrossum turned out that I just needed to remove the stdlib `typing.py` from conda.

smarie pointed this out earlier but I failed to see it the first pass.

@ilevkivskyi haha for the openAI gym library, currently you have to use 3.5.2 and in research it is really frowned upon to digress from reaching your goal as fast as you can ;-)

Also compiling tensorflow takes about an hour, so there are these tools that makes upgrade a bit of a hassel.

bottomline: I got things to work! thanks everyone:)
