### ISSUE TITLE
TypeVar equality broken?

### ISSUE THREAD

**Issue by pitrou** [python/typing#512]
This looks unexpected to me:
```
>>> import typing
>>> typing.TypeVar('T') == typing.TypeVar('T')
False
>>> 
```

**Comment by ilevkivskyi** [comment]
FWIW this is actually intentional. I think it was discussed briefly on this tracker, the main motivation is that from the point of view of static type checkers two type variables even with the same name can be different, they follow special scoping rules specified by PEP 484, for example:
```python
T = TypeVar('T')

def f(x: T) -> T: ...  # the two T's here are the same
def g(x: T) -> T: ... # the two T's here are the same, but different from the two T's above 
```
Also this is how type variables work in some other statically typed languages with generics/templates/etc. They get (re-)bound by a class or function definition.

I however don't have any strong opinion on their runtime behavior. @gvanrossum may add to this.

**Comment by gvanrossum** [comment]
Why would you ever want to compare TypeVars?

**Comment by pitrou** [comment]
This occurred during unit testing.

**Comment by pitrou** [comment]
Sorry, a bit more context: I was trying to add serialization support for typing hints in [cloudpickle](https://github.com/cloudpipe/cloudpickle) (see issue #511), and tried to use `assertEqual` to compare the original type and the unpickled result.

**Comment by gvanrossum** [comment]
Hm, I'd expect a TypeVar to be pickled as a reference, not as a value (just
like references to classes and functions). Though for that to work we'd
need to add __module__ to TypeVars.

**Comment by ilevkivskyi** [comment]
> Hm, I'd expect a TypeVar to be pickled as a reference, not as a value (just like references to classes and functions). Though for that to work we'd need to add ``__module__`` to TypeVars.

If we all agree that type variables should be treated as "immutable", i.e. ``copy(T) is T`` and ``loads(dumps(T)) is T`` then I can make a PR for this.

**Comment by gvanrossum** [comment]
There is no API to mutate a TypeVar and IMO there shouldn't be -- conceptually it really is just a *token*. So I agree. Hopefully this is acceptable to Antoine?

**Comment by pitrou** [comment]
Yes, it sounds ok.
