### ISSUE TITLE
TextIO/BinaryIO: Mismatch between documentation and implementation

### ISSUE THREAD

**Issue by srittau** [python/typing#518]
The [typing documentation](https://docs.python.org/3/library/typing.html) for 3.6.4rc1 at states:

> This (`typing.io`) defines the generic type `IO[AnyStr]` and aliases `TextIO` and `BinaryIO` for respectively `IO[str]` and `IO[bytes]`.

In the current implementation `TextIO` and `BinaryIO` are not aliases, but instead derived from `IO`. I am not sure whether this is a documentation or implementation problem, but the current implementation causes problems, since values of type `IO[...]`, and especially `IO[Any]` can not be assigned where `TextIO` or `BinaryIO` is expected.

See python/typeshed#1780 for a real-world example.

**Comment by gvanrossum** [comment]
It's both a documentation problem *and* an implementation problem!

The documentation is factually wrong, and contradicts PEP 484. *But* this has also been a major nuisance (I've seen a bunch of code that tried to pass an IO[something] to TextIO or BinaryIO -- even stub files).

Alas, fixing the implementation would be tough, because the subclasses define additional APIs (e.g. TextIO.encoding) or widen the acceptable range of arguments (e.g. BinaryIO.write()).

So I say we should fix the docs first (in time for 3.6.4final!) and then consider what to do about it. (Perhaps the only reasonable course of action is to recommend using IO[] for arguments and TextIO/BinaryIO for return types.)

Can you file a blocker bpo issue for the CPython docs?

**Comment by srittau** [comment]
@gvanrossum I filed it as [bpo-32284](https://bugs.python.org/issue32284), but someone else needs to set the blocker priority.

**Comment by srittau** [comment]
The documentation has been fixed. I believe that the trend towards I/O protocols means that this issue is basically resolved.
