### ISSUE TITLE
Need a solution for long lines in Python 2 

### ISSUE THREAD

**Issue by stephenfin** [python/typing#534]
This is a continuation of #186 and, like that change, has also been reported to [mypy](python/mypy#4511). I propose reading onto the following line for comments:

```python
import collections
from typing import DefaultDict, List


def test(pools):
    really_long_attribute = collections.defaultdict(list)
    # type: DefaultDict[str, List[str]]
    for pool in pools:
        pass  # meaningful stuff in here
```

This seems clear enough and should require minimal changes to the parser. I'm happy to propose an amendment to the PEP, but I'd like to get some input first.

**Comment by ethanhs** [comment]
I'm -1 on this. I don't think it is needed and is not clear. People will get confused and sometimes think that types come on the line before the definition. If you find your lines are getting too long due to types, you should use an alias. This is much more logical and unambiguous. A line is a definite encapsulation of an idea, and I don't think breaking that is a good idea.

**Comment by gvanrossum** [comment]
Another solution is to add a backslash (\) to the end of the statement and
put the comment on the next line. There's nothing wrong with a backslash in
this situation. (In fact we should add this solution to PEP 8's section on
how to format types.)
