### ISSUE TITLE
super().__init__ doesn't work in explicit protocol subclasses

### ISSUE THREAD

**Issue by ilevkivskyi** [python/typing#572]
A possible solution is to append a call to existing `__init__` while overwriting (after the check for `_is_protocol=True`, where we unconditionally raise because protocols can't be instantiated). This way explicit non-protocol subclasses can use a protocol `__init__` as a "default constructor". Default implementations are already supported for other protocol members, so it is natural to expect that `__init__` is not different. See also https://github.com/python/mypy/issues/3823

cc: @JukkaL

**Comment by grahamc** [comment]
I have run in to this problem with @adisbladis, and he came up with this workaround:

```python
if not TYPE_CHECKING:
    from typing import Generic
    Protocol = Generic
    def runtime_checkable(f):
        return f
else:
    from typing_extensions import Protocol, runtime_checkable
```


_I accidentally commented this on #561 at first, my apologies._

**Comment by Yobmod** [comment]
Hi, I've just come across this in our testing when updating from 3.10.0.a4 to 3.10.0.rc1.
There's been some change made to protocols for 3.10.0 that change runtime bahaviour?

In my case, the protocol classes don't have an '__init__()', so I didn't expect them to cause an error, and they didn't with 3.8 or 3.9.

I can't see what the change is in the 3.10 release notes, maybe the fix for runtime_checkable protocols with no methods? (But we have methods, just no init().)

**Comment by grahamc** [comment]
@Yobmod this bug has been open for 3 years, I wonder if you did some research that ties such a very recent change to this bug in particular?

**Comment by hauntsaninja** [comment]
https://github.com/python/cpython/pull/27545

**Comment by Yobmod** [comment]
@hauntsninja Thanks for the heads-up! (I put in a workaround for now, but I'll check if fixed next rc).

**Comment by srittau** [comment]
Closing here as this has been filed to bpo.
