### ISSUE TITLE
Subclassing Callable

### ISSUE THREAD

**Issue by DaniGuardiola** [python/typing#617]
I have a bunch of types defined like this:

```python
t_wrapped_deferred_return = Dict[str, any]
t_deferred_return = Dict[str, any]
t_sync_return = Dict[str, str]
t_return = Union[t_sync_return, t_deferred_return]


class OperationCallable(Callable[[Stack, Union[bytes, None]], t_return]):
    type: str
```

Then I'm using a function typed with `OperationCallable` elsewhere, like this:

```python
some_instance.fn(**kwargs)
```

This is throwing a mypy (I assume, I'm using PyCharm) error:

```
'OperationCallable' object is not callable
```

Am I missing something? Is there a different way to go about this?

Thanks!

**Comment by gvanrossum** [comment]
You can't actually use `Callable` as a base class. If you don't get an error on that, you're probably not using mypy but just getting whatever errors PyCharm produces on its own (it has a sophisticated type inference engine, it just works different than mypy).

There is no bug here, please see our gitter channel for more help: https://gitter.im/python/typing

**Comment by ilevkivskyi** [comment]
This tracker is not about mypy. It is about runtime issues in the backport of `typing` to older versions of Python.

Anyway, this error is correct, because just by inheriting from `Callable` you don't make a class callable, you must implement the `__call__()` method. Also mypy shows `Invalid base class` for this code, see https://github.com/python/mypy/issues/4031.

**Comment by DaniGuardiola** [comment]
Thanks @gvanrossum and @ilevkivskyi, I'll ask on Gitter and check the mypy issue.
