### ISSUE TITLE
Backport `typing.OrderedDict`

### ISSUE THREAD

**Issue by JelleZijlstra** [python/typing#679]
As of 3.7, the standard library includes `typing.OrderedDict`, but it is missing from the backport in this repo.

**Comment by ilevkivskyi** [comment]
This is a good point! I think it totally makes sense to add `OrderedDict` to the Python 2 version of `typing`. For Python 3 it should go to `typing_extensions` (similar to how it is done for `DefaultDict`). This can all be done in the same PR since `typing_extensions` live in this same repo.

Would you like to make a PR?

**Comment by srittau** [comment]
Closing as the backport has been removed from this repo.
