### ISSUE TITLE
[Feature Inquiry] Runtime @overload information

### ISSUE THREAD

**Issue by Tinche** [python/typing#711]
Hello,

this issue was originally filed over at https://github.com/python/mypy, but this might be a better place for it.

The @overload functionality is very useful. It would be even more useful if we could access the overloads programmatically, during runtime. To give a little context, I'm the author of [cattrs](https://github.com/Tinche/cattrs), which uses runtime type information heavily for de/serialization purposes.

For example, given a class like:
```
from typing import overload
import attr


@attr.s
class Test:
    @overload
    def a(self, b: int) -> int:
        ...

    @overload
    def a(self, b: float) -> float:
        ...

    def a(self, x):
        return x
```

It would be amazing if `Test.a` (or just `Test`) could be inspected for all overloads. As far as I can see, this information gets completely lost at runtime. I'm not sure what amount of black magic would make this possible?

I would be happy to go into more detail about why this would be very useful to be able to do if the authors are unconvinced of its utility.

Over at the original issue, @ethanhs mentioned this might even be technically impossible to do right now, so I'd be interested in brainstorming workarounds too.

**Comment by gvanrossum** [comment]
Could you link to the specific original issue? There are over 1000 issues at mypy, of which over 100 mention "overload"...

Anyway, the only way I see this working without changes to the `@overload` API would be to have a runtime `@overload` implementation that inspects the stack of its caller.

The good news is that you won't have to wait for us to do it! You can use the following little sequence to substitute your own `@overload` implementation at runtime, while letting mypy and other static type checkers still see the standard definition:
```
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from typing import overload
else:
    from my_hacks import overload
```
It's probably also possible to fool mypy and other type checkers into believing that `my_hacks` defines the standard `@overload` definition by including a `my_hacks.pyi` file that contains simply
```
from typing import overload as overload
```
(The `as overload` is important since it signals to type checkers that it is also exported, see PEP 484.)

**Comment by Tinche** [comment]
Here's the link, sorry: https://github.com/python/mypy/issues/8639.

Thanks for the tip, I will play around with this. My first hunch was being naughty with the stack too.

**Comment by gvanrossum** [comment]
> Thanks for the tip, I will play around with this. My first hunch was being naughty with the stack too.

Good luck. I really don't see a way around this, given the way decorators are implemented. (For a similar case, defining getter/setter methods, the `@property` decorator has some ugly syntax to carry over state between the getter and setter definitions.)

I'll close this now, but let us know if you manage to productize this.

**Comment by JelleZijlstra** [comment]
In a class definition you could potentially do this with a custom metaclass that messes with the class namespace dictionary.
