### ISSUE TITLE
get_type_hints NameError: name is not defined for nested classes in functions

### ISSUE THREAD

**Issue by ltworf** [python/typing#797]
Take this example code:

```python

from typing import *

def test():
    class A(NamedTuple):
        a: int
    class B(NamedTuple):
        a: A
        b: int
    return get_type_hints(B)

test()
```

Of course this works fine:

```
python3.9 test.py 
{'a': <class '__main__.test.<locals>.A'>, 'b': <class 'int'>}
```

But it no longer does in python 3.10

```
python3.10 test.py 
Traceback (most recent call last):
  File "/tmp/test.py", line 11, in <module>
    print(test())
  File "/tmp/test.py", line 9, in test
    return get_type_hints(B)
  File "/usr/lib/python3.10/typing.py", line 1595, in get_type_hints
    value = _eval_type(value, base_globals, localns)
  File "/usr/lib/python3.10/typing.py", line 305, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/usr/lib/python3.10/typing.py", line 607, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'A' is not defined
```

Am I doing something wrong? I understand that the context is getting lost but I'm not sure how should it be obtained back?

Is this thing supported?

**Comment by gvanrossum** [comment]
Duplicate issue. The workaround is `get_type_hints(..., locals=locals())`.

**Comment by ltworf** [comment]
In reality, in my use case, `B` is returned and `get_type_hints` called elsewhere, so the workaround does not work.

```python
from typing import *

def test():
    class A(NamedTuple):
        a: int
    class B(NamedTuple):
        a: A
        b: int
    return B

print(get_type_hints(test(), localns=locals()))
```

But it seems that calling it in the same context resolves the values and makes it possible to call it later on as well, like this.

```python

from typing import *

def test():
    class A(NamedTuple):
        a: int
    class B(NamedTuple):
        a: A
        b: int
    get_type_hints(B, localns=locals())
    return B

print(get_type_hints(test(), localns=locals()))
```

**Comment by gvanrossum** [comment]
A more traditional workaround is to just make the classes global.

**Comment by ltworf** [comment]
Hehe true true.

I only use that in test cases but I have no idea if anyone uses it like that, so I must count it as a breaking API change, new major version, and so on.

**Comment by haakonvt** [comment]
> Duplicate issue. The workaround is `get_type_hints(..., locals=locals())`.

I think it should be `localns=` 😄

**Comment by wilson0x4d** [comment]
this issue comes up for me as a top result on google for this error. for me, this is caused by a circular dependency on the type using itself in a type hint within its own definition. i was able to resolve this problem in my scenario by using `ForwardRef`:

```python
CircularObj = typing.ForwardRef('CircularObj')
class CircularObj:
    circular:CircularObj
typing.get_type_hints(CircularObj)
```

both the `ForwardRef` before class definition and the call to `get_type_hints` after class definition are required.

this avoids the need for `localns=` hackery (since changing the underlying library where this error occurs is simply not an option), and provides for a workaround without burdening library authors that are relying on `typing` to perform type reflection. hopefully this helps others having this same issue.

**Comment by jgarvin** [comment]
I am trying to write a unit test that ensures a decorator throws when the type annotations on a function are not what it expects. I can't move the function to the top level because then the decorator would run outside the test. I can manually run the decorator instead of using the `@` syntax, but this is silly, this should obviously work, behavior shouldn't vary based on whether definitions are nested.

**Comment by JelleZijlstra** [comment]
In Python 3.14, you will be able to use something like `annotationlib.get_annotations(func, format=Format.FORWARDREF)` to do what you want.
