### ISSUE TITLE
Incosistent behaviour of `list[]` and `typing.List[]` (and other generics)

### ISSUE THREAD

**Issue by sobolevn** [python/typing#820]
While reading [PEP-0585](https://www.python.org/dev/peps/pep-0585) I haven't seen any mentions that `list[]` would work differently compared to `typing.List[]`

Today I got hit by this:

```python
>>> from typing import List
>>> List[int]  # no error, ok
typing.List[int]
>>> List[1]  # error, ok
Traceback (most recent call last):
  ...
TypeError: Parameters to generic types must be types. Got 1.
>>> list[int]  # no error, ok
list[int]
>>> list[1]   # no error, not ok
list[1]
```

For some reason new syntax does not call `typing._type_check`. This also results in this problem for us in `hypothesis`: https://github.com/HypothesisWorks/hypothesis/issues/3016

I am using `python@3.9.1`

Is it a bug or a feature? 🙂

**Comment by ethanhs** [comment]
This should probably be filed against CPython, as that's where the list object lives. But I'm not sure if this is a bug, as I believe this was intentional to keep list's implementation simple and cheap. But it should be simple enough to reject items that are not type objects, so I'd file on bugs.python.org

**Comment by JelleZijlstra** [comment]
Yes, this is intentional for implementation simplicity. I would not support changing it, since overly strict runtime APIs tend to make it harder to develop new type system features in the future. For example, Ethan's suggestion of accepting only type objects would reject `list[list[int]]`, because `list[int]` is not itself a type object.

**Comment by sobolevn** [comment]
One more question: what about `ForwardRef`? Their behaviour is also different.

Example:

```python
from typing import List
from dataclasses import dataclass

@dataclass 
class UserOld:
    following: List['User']

@dataclass 
class UserNew:
    following: list['User']

print(UserOld.__annotations__)
# {'following': typing.List[ForwardRef('User')]}

print(UserNew.__annotations__)
# {'following': list['User']}
```

Note, that `UserNew` does not wrap `'User'` in `ForwardRef`. Is it also intentional?

**Comment by JelleZijlstra** [comment]
Yes, that's an internal typing.py API that isn't applied by the builtin typing support. In general the trend is to move away from the runtime magic in typing.py in favor of simpler builtin implementations.
