### ISSUE TITLE
Custom types with parameters

### ISSUE THREAD

**Issue by Arthurdw** [python/typing#887]
Ok so I'm trying to implement some custom types, yet my IDE and MyPy don't recognise it properly.

This is the code snippet:

```py
from typing import Union


class MissingType(type):
    ...


MISSING = MissingType


class APINullable(type):
    @staticmethod
    def __class_getitem__(item):
        print(f"Getting Union[{item.__name__}, MISSING]")
        return Union[item, MISSING]


lol: APINullable[str] = MISSING
lol2: APINullable[str] = "test"
lol3: APINullable[str] = 123

for i in (lol, lol2, lol3):
    print(i, type(i), i is MISSING)

```
Which has this output:
```
Getting Union[str, MISSING]
Getting Union[str, MISSING]
Getting Union[str, MISSING]
<class '__main__.MissingType'> <class 'type'> True
test <class 'str'> False
123 <class 'int'> False
``` 
And thats totally expected and right, but for some reason Pycharm, VSCode *(w Pylance)* and MyPy don't recognise this. This is the MyPy output:
```js
test.py:18: error: "APINullable" expects no type arguments, but 1 given
test.py:18: error: Incompatible types in assignment (expression has type "Type[MissingType]", variable has type "APINullable")
test.py:19: error: "APINullable" expects no type arguments, but 1 given
test.py:19: error: Incompatible types in assignment (expression has type "str", variable has type "APINullable")
test.py:20: error: "APINullable" expects no type arguments, but 1 given
test.py:20: error: Incompatible types in assignment (expression has type "int", variable has type "APINullable")
Found 6 errors in 1 file (checked 1 source file)
```

Idk if I should make the issue here or in the mypy repo, but since its not recognised in different editors neither I'm posting it here first.

**Comment by hauntsaninja** [comment]
Type checkers don't care what you do in `__class_getitem__` since you could do arbitrarily horrible Turing complete things. The only way to tell type checkers about generic types are the ways outlined here: https://mypy.readthedocs.io/en/stable/generics.html

Here's an implementation of a MISSING sentinel typing pattern in mypy: https://github.com/python/mypy/blob/725a24a82fdf79521db5d0c43549e8731f793c55/mypy/stubtest.py#L31

Good forums for this kind of question are https://github.com/python/typing/discussions or https://gitter.im/python/typing
