### ISSUE TITLE
Standardize `typeshed._typeshed.NoneType`

### ISSUE THREAD

**Issue by KotlinIsland** [python/typing#939]
https://github.com/python/mypy/issues/11539#issuecomment-968245730

**Comment by srittau** [comment]
I'm not sure what this issue is about. `_typeshed` is a stub for typeshed's internal use, although we give certain stability guarantees as outlined in `_stdlib/typeshed/README.md`. There's also consensus to add more stable types to `typing_extensions` (possibly in a sub-module), see python/typeshed#5912.

**Comment by JelleZijlstra** [comment]
What "standardization" do you propose concretely? I'm not sure we need anything more formal than we have already.

**Comment by KotlinIsland** [comment]
okay
